# Generated by Django 5.1.15 on 2026-03-18 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cndr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'cndr',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('daily_date', models.DateField(blank=True, null=True)),
                ('cndr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='pnogo.cndr')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
